// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen -source=usecase.go -destination=./mocks/usecase_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	entity "main/internal/domain/entity"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateSubscription mocks base method.
func (m *MockRepository) CreateSubscription(ctx context.Context, input entity.Subscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubscription", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSubscription indicates an expected call of CreateSubscription.
func (mr *MockRepositoryMockRecorder) CreateSubscription(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubscription", reflect.TypeOf((*MockRepository)(nil).CreateSubscription), ctx, input)
}

// DeleteSubscription mocks base method.
func (m *MockRepository) DeleteSubscription(ctx context.Context, subscriptionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubscription", ctx, subscriptionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSubscription indicates an expected call of DeleteSubscription.
func (mr *MockRepositoryMockRecorder) DeleteSubscription(ctx, subscriptionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubscription", reflect.TypeOf((*MockRepository)(nil).DeleteSubscription), ctx, subscriptionID)
}

// GetListSubs mocks base method.
func (m *MockRepository) GetListSubs(ctx context.Context, userID uuid.UUID, limit, offset int) ([]entity.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListSubs", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]entity.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListSubs indicates an expected call of GetListSubs.
func (mr *MockRepositoryMockRecorder) GetListSubs(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListSubs", reflect.TypeOf((*MockRepository)(nil).GetListSubs), ctx, userID, limit, offset)
}

// GetOverlappingSubscriptions mocks base method.
func (m *MockRepository) GetOverlappingSubscriptions(ctx context.Context, userID uuid.UUID, serviceName string, start, end time.Time) ([]entity.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOverlappingSubscriptions", ctx, userID, serviceName, start, end)
	ret0, _ := ret[0].([]entity.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOverlappingSubscriptions indicates an expected call of GetOverlappingSubscriptions.
func (mr *MockRepositoryMockRecorder) GetOverlappingSubscriptions(ctx, userID, serviceName, start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOverlappingSubscriptions", reflect.TypeOf((*MockRepository)(nil).GetOverlappingSubscriptions), ctx, userID, serviceName, start, end)
}

// GetSubscriptionByID mocks base method.
func (m *MockRepository) GetSubscriptionByID(ctx context.Context, subscriptionID uuid.UUID) (entity.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptionByID", ctx, subscriptionID)
	ret0, _ := ret[0].(entity.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptionByID indicates an expected call of GetSubscriptionByID.
func (mr *MockRepositoryMockRecorder) GetSubscriptionByID(ctx, subscriptionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionByID", reflect.TypeOf((*MockRepository)(nil).GetSubscriptionByID), ctx, subscriptionID)
}

// UpdateSubscription mocks base method.
func (m *MockRepository) UpdateSubscription(ctx context.Context, input entity.Subscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubscription", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSubscription indicates an expected call of UpdateSubscription.
func (mr *MockRepositoryMockRecorder) UpdateSubscription(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubscription", reflect.TypeOf((*MockRepository)(nil).UpdateSubscription), ctx, input)
}
